spring:
  application:
    name: customer
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - classpath:application-common.yaml
      - optional:classpath:application-${spring.profiles.active}.yaml
  docker:
    compose:
      file: ../compose.yaml

server:
  port: 8084
