spring:
  application:
    name: customer
  profiles:
    active: local
    include: common
  config:
    import:
      - classpath:application-common.yaml
      - optional:classpath:application-${spring.profiles.active}.yaml

server:
  port: 8084
